title: Hosting an image in Google Drive
hero_image: images/banner.png
description: generic-google-drive-image description
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2020-09-16"
steps:
  - title: Hosting an image in Google Drive
